#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        server_name _;
        location / {
                return 200 'Hello World!';
        }
}" > /etc/nginx/sites-available/default

# Restart Nginx
kill $(cat /var/run/nginx.pid)
nginx

# End script
exit 0

