#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
apt-get -y update
apt-get -y install nginx

# set the custom header name and value
HEADER_NAME="X-Served-By"
HEADER_VALUE=$(hostname)

# configure Nginx to add the custom header
sed -i "s|.*server_tokens.*;|server_tokens off;\n\tadd_header $HEADER_NAME $HEADER_VALUE;|" /etc/nginx/nginx.conf


# Create a firts index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# 404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Redirection
sed -i 's/location \/redirect_me {/location \/redirect_me {\n\treturn 301 https:\/\/www.youtube.com/@chineduelijah9785\/;/' /etc/nginx/sites-available/default

# Test configuration
nginx -t

# Restart nginx
service nginx restart
