#!/usr/bin/env bash
# Installs and configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend realchinedcode.tech
        bind 0:80
        default_backend realchinedcode.tech_backend

backend realchinedcode.tech_backend
        balance roundrobin
        server 143984-web-01 54.162.41.114:80 check
        server 143984-web-02 3.83.253.198:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo service haproxy restart
