#!/usr/bin/env bash
# Displays Best School 10 times using while loop
#   On the 9th iteration, displays "Hi" before "Best School"

incr=0

while [ $incr -lt 10 ]
do
    if [ $incr -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    (( incr++ ))
done
