#!/usr/bin/env bash
# This Script connects to the server 54.90.29.165 using the users private key
# stored in a file school Found in the users home directory

ssh -i ~/.ssh/school ubuntu@54.90.29.165
